image: docker:latest
services:
  - docker:dind
 
stages:
  - build
  - deploy

# Джоба для ветки prod:
build-prod:
  only:
    - prod
  stage: build
  script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} https://gitlab.magic-egg.net:5005
    - docker build --pull -t $GITLAB_REGISTRIES_URL/$IMAGE_MASTER:$CI_COMMIT_BRANCH .
    - docker push $GITLAB_REGISTRIES_URL/$IMAGE_MASTER:$CI_COMMIT_BRANCH

deploy-prod:
  when: manual
  stage: deploy
  only:
    - prod
  environment:
    name: "production"
    url: "https://lk.kupit-zerno.com"
  script:
    - mkdir -p ~/.ssh
    - echo "${PROD_PRIVATE_KEY}" |tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh -t -t -T -oStrictHostKeyChecking=no -oUserKnownHostsFile=/dev/null publisher@lk.kupit-zerno.com "docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} https://gitlab.magic-egg.net:5005 && bash waiter.sh $GITLAB_REGISTRIES_URL/$IMAGE_MASTER:$CI_COMMIT_BRANCH 3080 && docker logout"

# deploy master
deploy-master:
  only:
    - "master"
  stage: deploy
  environment: 
    name: "development"
    url: "$DOMEN_MASTER"
  before_script:
    - mkdir -p ~/.ssh
    - echo "$DEV_SERVER_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H $DEV_SERVER_IP >> ~/.ssh/known_hosts
  script:
    - printf "NODE_PATH=src/\n" > web-environment.env
    - scp -r ./web-environment.env $DEV_SERVER_USERNAME@${DEV_SERVER_IP}:~/
    - ssh $DEV_SERVER_USERNAME@$DEV_SERVER_IP "docker login $GITLAB_REGISTRIES_URL -u $GITLAB_LOGIN -p $GITLAB_TOKEN;docker stop $CONTAINER_NAME_MASTER;docker rm $CONTAINER_NAME_MASTER --force;docker pull $GITLAB_REGISTRIES_URL/$IMAGE_MASTER;docker run --restart always -p $PORT_MASTER --name $CONTAINER_NAME_MASTER --env-file web-environment.env -d $GITLAB_REGISTRIES_URL/$IMAGE_MASTER"


# jobs for all, except master:
build-dev:
  except:
    - master
    - prod
  stage: build
  script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} https://gitlab.magic-egg.net:5005
    - docker build --pull -t $GITLAB_REGISTRIES_URL/$IMAGE_DEV:$CI_COMMIT_BRANCH .
    - docker push $GITLAB_REGISTRIES_URL/$IMAGE_DEV:$CI_COMMIT_BRANCH

deploy-dev:
  except:
    - master
    - prod
  stage: deploy
  environment: 
    name: "development"
    url: "$DOMEN_DEV"
  variables:
    GIT_STRATEGY: clone
  before_script:
    - mkdir -p ~/.ssh
    - echo "$DEV_SERVER_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H $DEV_SERVER_IP >> ~/.ssh/known_hosts
  script:
    - printf "NODE_PATH=src/\n" > web-environment.env
    - scp -r ./web-environment.env $DEV_SERVER_USERNAME@${DEV_SERVER_IP}:~/
    - ssh $DEV_SERVER_USERNAME@$DEV_SERVER_IP "docker login $GITLAB_REGISTRIES_URL -u $GITLAB_LOGIN -p $GITLAB_TOKEN;docker stop $CONTAINER_NAME_DEV;docker rm $CONTAINER_NAME_DEV --force;docker pull $GITLAB_REGISTRIES_URL/$IMAGE_DEV:$CI_COMMIT_BRANCH;docker run --restart always -p $PORT_DEV --name $CONTAINER_NAME_DEV --env-file web-environment.env -d $GITLAB_REGISTRIES_URL/$IMAGE_DEV:$CI_COMMIT_BRANCH"
