image: docker:latest
services:
  - docker:dind
 
stages:
  # - build
  - deploy
  # - debug

# # Билд джобы
# build-master:
#   stage: build
#   only: 
#     - master
#   script:
#     - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} https://gitlab.magic-egg.net:5005
#     - docker build --pull -t $GITLAB_REGISTRIES_URL/$IMAGE_MASTER:master .
#     - docker push $GITLAB_REGISTRIES_URL/$IMAGE_MASTER:master

# build-dev:
#   stage: build
#   except: 
#     - master
#   script:
#     - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} https://gitlab.magic-egg.net:5005
#     - docker build --pull -t $GITLAB_REGISTRIES_URL/$IMAGE_DEV:$CI_COMMIT_BRANCH .
#     - docker push $GITLAB_REGISTRIES_URL/$IMAGE_DEV:$CI_COMMIT_BRANCH


# Деплой
deploy-dev:
  stage: deploy
  except:
    - master
  environment: 
    name: "development"
    url: "https://grain-dev.me-interactive.net"
  before_script:
    - mkdir -p ~/.ssh
    - echo "$DEV_SERVER_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H $DEV_SERVER_IP >> ~/.ssh/known_hosts
  script:
    - docker ps -a

# deploy-master:
#   stage: deploy
#   only:
#     - master
#   environment: 
#     name: "pre-prod"
#     url: "https://grain.me-interactive.net"
#   before_script:
#     - mkdir -p ~/.ssh
#     - echo "$DEV_SERVER_KEY" | tr -d '\r' > ~/.ssh/id_rsa
#     - chmod 600 ~/.ssh/id_rsa
#     - eval "$(ssh-agent -s)"
#     - ssh-add ~/.ssh/id_rsa
#     - ssh-keyscan -H $DEV_SERVER_IP >> ~/.ssh/known_hosts
#   script:
#     - ssh publisher@host.me-interactive.net "bash publish.sh $GITLAB_REGISTRIES_URL/$IMAGE_MASTER:master 127.42.42.110:1016 grain_master"

deploy-prod:
  stage: deploy
  when: manual
  only:
    - master
  environment: 
    name: "production"
    url: "https://lk.kupit-zerno.com"
  before_script:
    - mkdir -p ~/.ssh
    - echo "$PROD_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H lk.kupit-zerno.com >> ~/.ssh/known_hosts
  script:
    - ssh publisher@lk.kupit-zerno.com "bash waiter.sh $GITLAB_REGISTRIES_URL/$IMAGE_MASTER:master 3080"

