image: docker:latest
services:
  - docker:dind
 
stages:
  - build
  - deploy
  - debug

# Билд джобы (master-only)
build-master:
  stage: build
  only: 
    - master
  script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} https://gitlab.magic-egg.net:5005
    - docker build --pull -t $GITLAB_REGISTRIES_URL/$IMAGE_MASTER:master .
    - docker push $GITLAB_REGISTRIES_URL/$IMAGE_MASTER:master

build-dev:
  stage: build
  except: 
    - master
  script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} https://gitlab.magic-egg.net:5005
    - docker build --pull -t $GITLAB_REGISTRIES_URL/$IMAGE_DEV:$CI_COMMIT_BRANCH .
    - docker push $GITLAB_REGISTRIES_URL/$IMAGE_DEV:$CI_COMMIT_BRANCH


# Деплой
deploy-dev:
  stage: deploy
  except:
    - master
  environment: 
    name: "development"
    url: "https://grain-dev.me-interactive.net"
  script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} https://gitlab.magic-egg.net:5005
    - docker stop grain_dev && docker rm grain_dev
    - docker pull $GITLAB_REGISTRIES_URL/$IMAGE_DEV:$CI_COMMIT_BRANCH
    - docker run -d --name grain_dev --hostname grain_dev -p 127.42.42.110:1006:3000 -e NODE_OPTIONS=--openssl-legacy-provider $GITLAB_REGISTRIES_URL/$IMAGE_DEV:$CI_COMMIT_BRANCH 

deploy-master:
  stage: deploy
  only:
    - master
  environment: 
    name: "pre-prod"
    url: "https://grain.me-interactive.net"
  script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} https://gitlab.magic-egg.net:5005
    - docker pull $GITLAB_REGISTRIES_URL/$IMAGE_MASTER:master
    - docker stop grain_master && docker rm grain_master
    - docker run -d --name grain_master --hostname grain_master -p 127.42.42.110:1016:3000 -e NODE_OPTIONS=--openssl-legacy-provider $GITLAB_REGISTRIES_URL/$IMAGE_MASTER:master


deploy-prod:
  stage: deploy
  when: manual
  only:
    - master
  environment: 
    name: "production"
    url: "https://lk.kupit-zerno.com"
  before_script:
    - mkdir -p ~/.ssh
    - echo "$PROD_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - ssh-keyscan -H lk.kupit-zerno.com >> ~/.ssh/known_hosts
  script:
    - ssh publisher@lk.kupit-zerno.com "bash waiter.sh $GITLAB_REGISTRIES_URL/$IMAGE_MASTER:master 3080"

